[gitea_group]
gitea_node

[npm_group]
npm_node

[jenkins_group]
jenkins_node

[portainer_group]
portainer_node

[harbor_group]
harbor_node

[traefik_group]
traefik_node

[pve_group]
pve1 ansible_host=192.168.1.x
pve3 ansible_host=192.168.1.x

[pve_group:vars]
ansible_user=root

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa