---
- name: Install system dependencies
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Install Docker
  shell: "curl -fsSL https://get.docker.com | sh"
  args:
    creates: /usr/bin/docker

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

# --- 1. INSTALL DOCKER COMPOSE (MANUAL) ---
- name: Create directory for Docker CLI plugins
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose (Manual Binary Download)
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755' # Make executable immediately (+x)

# --- 2. SERVER PREPARATION ---
- name: Create installation directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ gitea_install_dir }}"

- name: Create secure SSL directory
  file:
    path: "{{ gitea_ssl_dir }}"
    state: directory
    mode: '0700'
    owner: '1000'
    group: '1000'

# --- 3. SET UP TRUST (HOST LEVEL) ---
- name: Upload Gitea CA to Host System
  copy:
    # Ansible возьмет любой файл из папки files/trust/
    src: "{{ item }}"
    dest: "{{ gitea_ssl_dir }}/root_ca.crt"
    mode: '0644'
    owner: '1000'
    group: '1000'
  with_fileglob:
    - "{{ role_path }}/files/trust/*"
  when: item is not match(".*\\.template$")
  notify: Restart Gitea

- name: Create custom CA bundle for Gitea
  shell: >
    if [ -f "{{ gitea_ssl_dir }}/root_ca.crt" ]; then
      cat /etc/ssl/certs/ca-certificates.crt "{{ gitea_ssl_dir }}/root_ca.crt" > "{{ gitea_ssl_dir }}/gitea_bundle.crt";
    else
      cat /etc/ssl/certs/ca-certificates.crt > "{{ gitea_ssl_dir }}/gitea_bundle.crt";
    fi
  notify: Restart Gitea

- name: Fix permissions on custom bundle
  file:
    path: "{{ gitea_ssl_dir }}/gitea_bundle.crt"
    mode: '0644'
    owner: '1000'
    group: '1000'
  notify: Restart Gitea

# --- 4. DOCKER CONFIGURATION ---
- name: Generate docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ gitea_install_dir }}/docker-compose.yml"
  notify: Restart Gitea

# --- 5. START ---
- name: Ensure persistent data volume exists
  command: docker volume create gitea_data
  register: volume_create
  changed_when: "volume_create.rc == 0 and 'gitea_data' not in volume_create.stdout"
  failed_when: false

- name: Start Gitea Stack
  community.docker.docker_compose_v2:
    project_src: "{{ gitea_install_dir }}"
    state: present