---
- name: Install system dependencies
  apt:
    name: [curl, git]
    state: present
    update_cache: yes

- name: Ensure certs directory exists
  file:
    path: "{{ jenkins_install_dir }}/certs"
    state: directory
    mode: "0755"

- name: Copy custom CA certificate
  copy:
    # Ansible возьмет любой файл из папки files/trust/
    src: "{{ item }}"
    dest: "{{ jenkins_install_dir }}/certs/root_ca.crt"
    mode: "0644"
  with_fileglob:
    - "roles/jenkins/files/trust/*"
  notify: Restart Jenkins

- name: Install Docker
  shell: "curl -fsSL https://get.docker.com | sh"
  args:
    creates: /usr/bin/docker

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create app directory
  file:
    path: "{{ jenkins_install_dir }}"
    state: directory
    mode: "0755"

- name: Ensure data directory permissions are ROOT
  file:
    path: "{{ jenkins_install_dir }}/data"
    state: directory
    owner: "root"
    group: "root"
    recurse: yes

- name: Ensure Jenkins init scripts directory exists
  file:
    path: "{{ jenkins_install_dir }}/data/init.groovy.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Render built-in node executor bootstrap
  template:
    src: init.groovy.d/00-disable-built-in-node.groovy.j2
    dest: "{{ jenkins_install_dir }}/data/init.groovy.d/00-disable-built-in-node.groovy"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart Jenkins

- name: Render Jenkins Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ jenkins_install_dir }}/Dockerfile"
    mode: "0644"
  notify: Restart Jenkins

- name: Copy Docker Compose template
  template:
    src: compose.yml.j2
    dest: "{{ jenkins_install_dir }}/compose.yml"
    mode: "0644"
  notify: Restart Jenkins

- name: Start Jenkins via Docker Compose
  command: docker compose up -d --build
  args:
    chdir: "{{ jenkins_install_dir }}"
  register: docker_output
  changed_when: "'Started' in docker_output.stdout or 'Recreated' in docker_output.stdout"
